#!/bin/bash --login

# send -15 twice to stop varchive server.
ps -ef | grep varchive-server.py | grep -v grep | awk '{print $2}' | xargs -I {} kill -15 {}
ps -ef | grep varchive-server.py | grep -v grep | awk '{print $2}' | xargs -I {} kill -15 {}
ps -ef | grep varchive-client | grep -v grep | awk '{print $2}' | xargs -I {} kill -15 {}
ps -ef | grep node | grep -i varchive | grep -v grep | awk '{print $2}' | xargs -I {} kill -15 {}

TOTAL=5
count=0
while ps -ef | grep varchive-server.py | grep -v grep; do
    ((count++))
    if [ $count -ge $TOTAL ]; then
        ps -ef | grep varchive-server.py | grep -v grep | awk '{print $2}' | xargs -I {} kill -9 {}
    fi
    sleep 1
done

count=0
while ps -ef | grep varchive-client | grep -v grep; do
    ((count++))
    if [ $count -ge $TOTAL ]; then
        ps -ef | grep varchive-client | grep -v grep | awk '{print $2}' | xargs -I {} kill -9 {}
    fi
    sleep 1
done

count=0
while ps -ef | grep node | grep -i varchive | grep -v grep; do
    ((count++))
    if [ $count -ge $TOTAL ]; then
        ps -ef | grep node | grep -i varchive | grep -v grep | awk '{print $2}' | xargs -I {} kill -9 {}
    fi
    sleep 1
done
