#!/bin/bash --login

# Get the directory of the script
SCRIPT_DIR=$(dirname "$0")
SCRIPT_PARENT_DIR=$(
    cd "$SCRIPT_DIR/.."
    pwd
)

# if ! $SCRIPT_DIR/varchive-checkInstall; then
#     echo "Some dependences have to be installed first. You will be asked to input your system password during the install process."
#     if ! open $SCRIPT_PARENT_DIR/install; then
#         echo "Install failed!" 1>&2
#         exit 1
#     fi
# fi

if ! ps -ef | grep varchive-server.py | grep -v grep; then
    cd "$SCRIPT_DIR/../server/src"
    nohup python3.9 varchive-server.py >>/tmp/varchive-server.log 2>&1 &
    cd - >/dev/null
fi

if ! ps -ef | grep ./varchive-client | grep -v grep; then
    cd "$SCRIPT_DIR"
    nohup ./varchive-client >>/tmp/varchive-client.log 2>&1 &
    cd - >/dev/null
    TOTAL=5
    count=0
    while ! curl http://localhost:5999/ >/dev/null 2>&1; do
        ((count++))
        if [ $count -ge $TOTAL ]; then
            echo "Failed: npm run dev!" 1>&2
            exit 1
        fi
        sleep 1
    done
    cat "/tmp/varchive-npm.log" | tail -n 7
fi

exit 0
